### ISSUE TITLE
Inscription error

### ISSUE THREAD

**Issue by ShiiFu** [Loodoor/template_blog#10]
Hi,

I am not able to register myself on your instance of this repository. When I submit the form with clicking on "Inscription" button, nothing is happening.

ShiiFu.

**Comment by Loodoor** [comment]
Hi,

that's a known bug, I am working on it. I think it's an error with the php code behind it, when I will have more info I will post here ;)

Thanks for your help :)

**Comment by Loodoor** [comment]
hi, i am a bit late, but we will be working on it during the next months

**Comment by Loodoor** [comment]
hi, it is now patched (in https://github.com/Loodoor/kyatchioru, using this template)
