### ISSUE TITLE
Research error

### ISSUE THREAD

**Issue by ShiiFu** [Loodoor/template_blog#8]
Hello,

On [this instance](http://wearecoders.hostux.fr/) of this repository I have an error when I search something : 
![image](https://cloud.githubusercontent.com/assets/10438692/19188610/2a017818-8c93-11e6-8310-d6316b97b2bc.png)

I don't investigate more.

ShiiFu

**Comment by Loodoor** [comment]
Hi !

Thanks for reporting the error (and sorry for being late to answer, github didn't tell me)

It will be patched in the next commit in both the repository and the website ;)
