### ISSUE TITLE
[Suggestion] Article preview on main page

### ISSUE THREAD

**Issue by ShiiFu** [Loodoor/template_blog#9]
Hi,

On the main page we can see the list of last articles.  
We can see their title and the beginning of the text.

I think to provide a better user experience, you should add the date of the article. Moreover at the end of the preview, you should add a button to navigate to the full article.

I hope my suggestion is useful.

ShiiFu

**Comment by Loodoor** [comment]
Hi !

For the date, yes, I will add it asap, but for the button, i don't really see the point because you can access the full article by clicking on the title :)

thanks for your help

**Comment by ShiiFu** [comment]
Hi,

Yes, we can access the full article by clicking on the title, but we must scroll up to do that. It should be better to click on a link or a button at the end of article preview which allow a better flow. 

Do you understand what I mean?

ShiiFu.

**Comment by Loodoor** [comment]
ow ok I understand now ! why not, i will add it on my todo list :)

**Comment by Loodoor** [comment]
that should be finished very soon on the instance https://github.com/Loodoor/kyatchioru :)
